
steps:
- id: 'terraform init'
  name: 'hashicorp/terraform:1.1.7'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      terraform init

# [START tf-apply]
- id: 'terraform apply'
  name: 'hashicorp/terraform:1.1.7'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |     
      terraform delete -auto-approve
# [END tf-apply]